# Generated by Django 4.1.4 on 2022-12-11 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_account_created_at_account_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='ending_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='batch',
            name='starting_time',
            field=models.TimeField(),
        ),
    ]
