# Generated by Django 4.1.4 on 2022-12-11 19:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_batch_ending_time_alter_batch_starting_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.batch'),
        ),
    ]
